name: "DEV DEPLOY"

on:
    push:
        branches:
            - '*'
        branches-ignore:
            - 'main'
            - 'qual'

permissions:
  id-token: write
  contents: read

jobs: 
    terraform:
        uses: ./.github/workflows/pipeline.yml
        with: 
            environment: dev
            aws-assume-role-arn: "arn:aws:iam::975050204462:role/github-actions-siga-app-pipeline"
            aws-region: "sa-east-1"
            aws-statefile-s3-bucket: "siga-app-sa-east-1-terraform-statefile"
            aws-lock-dynamodb-table: "siga-app-sa-east-1-terraform-lock"